name: Build & deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_backend:
    name: Build and run tests
    uses: ./.github/workflows/build.yml
    secrets: inherit

  build_docker:
    name: Build docker and publish
    needs: [ build_backend ]
    uses: ./.github/workflows/build_docker.yml
    secrets: inherit