name: Build & deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_backend:
    name: Build backend
    uses: ./.github/workflows/build.yml

  build_docker:
    name: Build docker
    needs: [ build_backend ]
    uses: ./.github/workflows/publish.yml